### ISSUE TITLE
http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz failing to download

### ISSUE THREAD

**Issue by eyaler** [BartyzalRadek/Multi-label-Inception-net#13]
>> Downloading inception-2015-12-05.tgz 0.0%Traceback (most recent call last):
  File "C:/Users/user/Multi-label-Inception-net/retrain.py", line 1028, in <module>
    tf.app.run()
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "C:/Users/user/Multi-label-Inception-net/retrain.py", line 883, in main
    maybe_download_and_extract()
  File "C:/Users/user/Multi-label-Inception-net/retrain.py", line 407, in maybe_download_and_extract
    _progress)
  File "C:\Anaconda3\lib\urllib\request.py", line 289, in urlretrieve
    % (read, size), result)
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 2134 out of 88931400 bytes>

Process finished with exit code 1

**Comment by BartyzalRadek** [comment]
http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz

Downloads without problems for me.
