### ISSUE TITLE
When I retrain my data, I get errors :(

### ISSUE THREAD

**Issue by Parkjini** [BartyzalRadek/Multi-label-Inception-net#3]
Hi,
I tried to train you model using own image data.
But, I have problems below.
How I can handle??

Thanks
---------------------------------------------------------------------------------------------------------------
Not a JPEG file: starts with 0x42 0x4d
Traceback (most recent call last):
  File "C:\Users\Jini\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1039, in _do_call
    return fn(*args)
  File "C:\Users\Jini\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1021, in _run_fn
    status, run_metadata)
  File "C:\Users\Jini\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\Jini\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid JPEG data, size 1015110
         [[Node: DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_DecodeJpeg/contents_0)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "retrain.py", line 1028, in <module>
    tf.app.run()
  File "C:\Users\Jini\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "retrain.py", line 938, in main
    jpeg_data_tensor, bottleneck_tensor)
  File "retrain.py", line 538, in cache_bottlenecks
    jpeg_data_tensor, bottleneck_tensor)
  File "retrain.py", line 496, in get_or_create_bottleneck
    bottleneck_tensor)
  File "retrain.py", line 381, in run_bottleneck_on_image
    {image_data_tensor: image_data})
  File "C:\Users\Jini\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 778, in run
    run_metadata_ptr)
  File "C:\Users\Jini\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Users\Jini\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "C:\Users\Jini\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid JPEG data, size 1015110
         [[Node: DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_DecodeJpeg/contents_0)]]

Caused by op 'DecodeJpeg', defined at:
  File "retrain.py", line 1028, in <module>
    tf.app.run()
  File "C:\Users\Jini\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "retrain.py", line 885, in main
    create_inception_graph())
  File "retrain.py", line 362, in create_inception_graph
    RESIZED_INPUT_TENSOR_NAME]))
  File "C:\Users\Jini\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\importer.py", line 308, in import_graph_def
    op_def=op_def)
  File "C:\Users\Jini\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\Jini\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Invalid JPEG data, size 1015110
         [[Node: DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_DecodeJpeg/contents_0)]]

**Comment by BartyzalRadek** [comment]
According to the error you are trying to run the net on non-JPEG image. 
Simply convert your images to JPEG with proper headers.

**Comment by Parkjini** [comment]
All of image are JPEG but this error occurs.
How can I do?
